
# GitHub Linguist Configuration for SpiralEcosystem
# Sovereign Native Language Recognition

overrides:
  "*.spiral": "SpiralScript"
  "*.sprl": "SpiralScript"
  "*.consciousness": "Consciousness"
  "*.htsx": "HTSX"
  "*.quantum": "QuantumAssembly"

# Vendor paths (exclude from language stats)
vendored:
  - "archive/**/*"
  - "node_modules/**/*"
  - "dist/**/*"
  - "build/**/*"

# Generated paths (exclude from language stats)  
generated:
  - "lib/generated/**/*"
  - "**/*.generated.*"

# Language definitions
languages:
  SpiralScript:
    type: programming
    color: "#8B5CF6"
    extensions:
      - ".spiral"
      - ".sprl"
    interpreters:
      - "spiral"
    
  Consciousness:
    type: programming  
    color: "#FFD700"
    extensions:
      - ".consciousness"
    interpreters:
      - "consciousness"
      
  HTSX:
    type: programming
    color: "#00FFFF" 
    extensions:
      - ".htsx"
    interpreters:
      - "htsx"
      
  QuantumAssembly:
    type: programming
    color: "#FF6B9D"
    extensions:
      - ".quantum"
    interpreters:
      - "quantum"
